--  테이블에서 조회수가 가장 높은 중고거래 게시물에 대한 첨부파일 경로를 조회하는 SQL문
-- 기본 : /home/grep/src/ + BOARD_ID/FILE_ID + FILE_ID


# SELECT CONCAT('/home/grep/src/',A.BOARD_ID,'/',B.FILE_ID, B.FILE_EXT) AS "FILE_PATH"
# FROM USED_GOODS_BOARD AS A
# INNER JOIN USED_GOODS_FILE AS B
# ON A.BOARD_ID = B.BOARD_ID
# WHERE A.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
# ORDER BY B.FILE_ID DESC;

SELECT CONCAT(CONCAT_WS("/", "/home/grep/src", F.BOARD_ID, F.FILE_ID), F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_FILE AS F
ON B.BOARD_ID = F.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC