--  자동차 종류가 '세단'인 자동차들 중 
--  10월에 대여를 시작한 기록이 있는 자동차 ID 리스트를 출력
SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS A
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE = "세단" AND B.START_DATE LIKE "2022-10%"
ORDER BY 1 DESC;