-- 보호소에서는 몇 시에 입양이 가장 활발하게 일어나는지 알아보려 합니다.
-- 0시부터 23시까지, 각 시간대별로 입양이 몇 건이나 발생했는지 조회하는 SQL문
-- 결과는 시간대 순으로 정렬

# SELECT HOUR(DATETIME) AS HOUR,
#        COUNT(HOUR(DATETIME)) AS COUNT
# FROM ANIMAL_OUTS
# GROUP BY HOUR
# ORDER BY HOUR


# WITH RECURSIVE GET_HOUR (HOUR)
#   AS (SELECT 0
#        UNION ALL
#       SELECT HOUR+1
#         FROM GET_HOUR
#        WHERE HOUR < 23
#      )
# SELECT G.HOUR, IFNULL(COUNT(ANIMAL_ID),'0')
# FROM GET_HOUR G
# LEFT OUTER JOIN ANIMAL_OUTS A ON G.HOUR = HOUR(DATETIME)
# GROUP BY 1
# ORDER BY 1

WITH RECURSIVE GET_HOUR
AS (
SELECT 0 AS HOUR# 초기값 0부터 시작
UNION ALL
SELECT HOUR+1
FROM GET_HOUR
WHERE HOUR<23)

SELECT A.HOUR,
       IFNULL(COUNT(ANIMAL_ID), '0') AS COUNT
FROM GET_HOUR AS A
LEFT JOIN ANIMAL_OUTS
ON A.HOUR = HOUR(DATETIME)
GROUP BY 1
ORDER BY 1
