-- 보호 시작일(ANIMAL_INS.DATETIME)보다 
-- 입양일(ANIMAL_OUTS.DATETIME)이 더 빠른 동물의 아이디와 이름을 조회하는 SQL문

-- SELECT ANIMAL_INS.ANIMAL_ID,
--       ANIMAL_INS.NAME

SELECT ANIMAL_INS.ANIMAL_ID,
       ANIMAL_INS.NAME
FROM ANIMAL_INS
INNER JOIN ANIMAL_OUTS 
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_OUTS.DATETIME < ANIMAL_INS.DATETIME
ORDER BY ANIMAL_INS.DATETIME
