--  FLAVOR (FIRST_HALF TABLE)
--  FLAVOR (ICECREAM_INFO TABLE)
-- 상반기 동안 각 아이스크림 성분 타입(INGREDIENT_TYPE)과 
-- 성분 타입에 대한 아이스크림의 총주문량(TOTAL_ORDER)을 총주문량이 작은 순서대로 조회

SELECT I.INGREDIENT_TYPE, 
       SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS F INNER JOIN ICECREAM_INFO AS I
ON F.FLAVOR = I.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY 2;
